spring:
  profiles:
    active: nonprod
---
spring:
  profiles: dev
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: nonprod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: prod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: test
---
spring:
  profiles: integration-test
  data.mongodb:
    host: localhost
    port: 27018
    database: local